POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1qbCIsImlkIjoiNWM2NmQ2NzM1ZDU1MzAzZDc5NWU5NDhlIiwiaWF0IjoxNTUwMzkzNjkzfQ.5f8K1nAYTBNfuQh2gjhBsP4HyKDPvmPm-6FPW1FsAwA

{
    "title": "Web-ohjelmointi",
    "author": "Heikki Virtanen",
    "url": "wordspot.ohjelmoidaan.com",
    "likes": 100
}